### ISSUE TITLE
Preparations for release on cppget.org

### ISSUE THREAD

**Issue by Rookfighter** [build2-packaging/vulkan-meta#1]
This meta package will be needed on cppget.org for also releasing imgui there. However there are still a few open points:
* there should be at least one example per major platform, i.e. Linux, MacOS, Windows and BSD
* the Vulkan SDK is not installed on bdep ci, so we cannot provide "successful" builds there
  * @boris-kolpackov can you give any hints how we should handle this? Would succeeding GitHub Actions be enough?
* Should the examples actually be changed to be "tests" (in the sense of smoke tests)?
* Is it better to have examples in a separate package (as it is now) or should they move to a unnamed examples (or tests) sub package as it is done for [libpthread-meta](https://github.com/build2-packaging/libpthread-meta)
  * @boris-kolpackov any preferences here?

**Comment by Rookfighter** [comment]
@Klaim and @Swat-SomeBug can you contribute examples e.g. for Windows or MacOS? Just very simple hello triangle kind of stuff which just shows that include directories and linker flags are exported correctly. I guess the package should be working to some extent already (since we use it for imgui), but it would still be nice for regression.

I could also work on a windows example, I am just not experienced with Vulkan at all.

**Comment by Swat-SomeBug** [comment]
I would have one proposal based on the following observations:

- When preparing tests we should consider something that can be built and executed in a CI env - maybe triangles are not the best for this purpose
- The test code needs to work cross platform and should be easy to maintain.

Currently `glfw` fits these requirements quite nicely and the build2 package has a CI executable test to check version and Vulkan requirements.

So we could add `glfw` as one of the upstreams in a `-tests` package, build it against Vulkan and execute the test.
What do you think? Too much effort/bloat?

Edit: I’m considering to use the `-meta` packages for `glfw`.

**Comment by Klaim** [comment]
Related: https://github.com/build2/build2/issues/202

**Comment by Klaim** [comment]
> @Klaim and @Swat-SomeBug can you contribute examples e.g. for Windows or MacOS? Just very simple hello triangle kind of stuff which just shows that include directories and linker flags are exported correctly. I guess the package should be working to some extent already (since we use it for imgui), but it would still be nice for regression.

Personally I didn't use Vulkan directly so far, always through a slightly higher layer (or engine). I think if you want that kind of test one way would be to look into the official (or recommended) vulkan tutorial and get the code from there and put it in a test exe here. But even then, it still need an implementation to run.

> So we could add glfw as one of the upstreams in a -tests package, build it against Vulkan and execute the test.
What do you think? Too much effort/bloat?

Not sure, maybe that could work well enough for basic validation yes.
Or making a vulkan-meta test package that also depends on glfw and is just a basic test.

In any way the examples in these kind  of projects are interractive so they are not really appropriate for CI tests unless you have a way to make them stop after some time and/or a way to input controls.

**Comment by Swat-SomeBug** [comment]
Ah… sorry I had tests in mind and not examples. Yes I agree, for examples, we can anyhow mostly not execute them. We can only get it to build.
Sorry for the confusion on my part, the thought was just in relation to release to cppget.org. As I understand, the package must have tests passing on at least one platform to be published.

**Comment by boris-kolpackov** [comment]
> there should be at least one example per major platform, i.e. Linux, MacOS, Windows and BSD
> the Vulkan SDK is not installed on bdep ci, so we cannot provide "successful" builds there
>    @boris-kolpackov can you give any hints how we should handle this? Would succeeding GitHub Actions be enough?
> As I understand, the package must have tests passing on at least one platform to be published.

While it would be good to have at least one successful build, this is not set in stone, we can definitely make exceptions, and I think this is a good candidate for such an exception. The aim of that guideline was to discourage people from submitting packages without any tests where at least a "smoke test" can easily be added.

Also, I think in this case, we can safely ignore BSDs -- I highly doubt Vulkan is in high demand there but if I am wrong and it is, someone more experienced can always help out. From our side for now we treat BSD as a non-graphical setup (i.e., we have no immediate plans to install any X packages or run Xvfb or some such on FreeBSD VMs). 

So, yes, please go ahead and submit this without any successful builds until we sort our Vulkan CI story out (per the issue @Klaim linked). Having tests pass on GitHub CI is a bonus.

> Should the examples actually be changed to be "tests" (in the sense of smoke tests)?

If they are examples first which also happen to act as tests, then I would keep them as examples (CI runs them all the same).

> Is it better to have examples in a separate package (as it is now) or should they move to a unnamed examples (or tests) sub package.

The two reasons to move tests/examples to separate packages are (1) strong reason: test-only dependencies (e.g., testing frameworks, etc) and (2) weak reason: large size of test sources and/or data (e.g., if you have huge input/output data to compare to or a really large number of tests). In this particular case, keeping them in the package seems like the way to go.

> So we could add glfw as one of the upstreams in a -tests package, build it against Vulkan and execute the test.
> What do you think? Too much effort/bloat?

I think it's an unnecessary complexity and thus an opportunity for more thing to go wrong. It's best to keep tests as minimal and single-purpose as possible so that when one fails, you know it most likely means that what you are testing is broken and not some other side-component that the test happened to pull in.

> Edit: I’m considering to use the -meta packages for glfw.

You mean you are thinking of renaming `glfw` to `glfw-meta`? The idea behind a meta-library is that it's for a system (or system-like) library like `pthread` or OpenGL and its main purpose is to just make linking to the library from `build2` projects more straightforward. If the library adds some functionality on top of the underlying library (as I understand `glfw` does), I think it stops fitting the meta library idea and becomes more of a "wrapper". In particular, there could plausibly be more than one such wrapper library which implement different ideas of how the wrapping should be done while ideally there should be only one meta-library.    

Also, on a personal note, I am currently on vacation (until 15th Aug) and may not be able to reply very promptly until back.

**Comment by Rookfighter** [comment]
> The test code needs to work cross platform and should be easy to maintain.

I agree on this, it would be nice to have a single cross platform test. However I disagree with the indirection by using e.g. glfw. The reason is if glfw depends on libvulkan-meta then we have a chicken egg problem and a test or example project can never work on the latest dev version of libvulkan-meta. It will just use whatever glfw depends on. Also if glfw adds linker flags for Vulkan, then tests do not truly reflect if the libvulkan-meta package is working or not. Personally I prefer to have tests which are isolated from side effects as much as possible.

> When preparing tests we should consider something that can be built and executed in a CI env - maybe triangles are not the best for this purpose

Actually any hello_triangle test could just render for a single frame, then we have tested compilation (include paths), linking (linker paths, libs) and execution (any runtime errors). I would say that is good enough for a smoke test.

**Comment by Rookfighter** [comment]
> The two reasons to move tests/examples to separate packages are (1) strong reason: test-only dependencies (e.g., testing frameworks, etc) and (2) weak reason: large size of test sources and/or data (e.g., if you have huge input/output data to compare to or a really large number of tests). In this particular case, keeping them in the package seems like the way to go.

Alright, so I will move the example into the libvulkan-meta package and make this repo a single package one. I will also leave the example as an example and won't turn it into test a test. I will also look into adding some content, to check linking against some symbols.

**Comment by Swat-SomeBug** [comment]
> You mean you are thinking of renaming glfw to glfw-meta?

No what I meant was to use the `*-Meta` packages. `glfw` depends on OpenGL and Vulkan, and current a big `if` block is used to set the necessary flags. Idea was to reuse these meta packages to avoid it.

**Comment by Swat-SomeBug** [comment]
@Rookfighter I will work on this and add a triangles example. Just need a couple of days for a PR.

**Comment by Rookfighter** [comment]
@Swat-SomeBug, thanks! Just one thing: I found this tutorial on Vulkan: https://vulkan-tutorial.com/Drawing_a_triangle/Setup/Instance

I think I will just use this `createInstance` code to setup a very simple smoke test (just call a Vulkan function to see if linking works). I will add this test inside the `libvulkan-meta` package. IMO, if that test works cross platform it should be good enough for now.

If you still feel like adding a full-fledged hello triangle example, that would be great! I would leave it up to you if you still want to add a full-fledged example. As far as I can see, such an example could be tedious to setup without using GLFW. So, I take back my statement. Feel free to use GLFW to setup an example if you wish. I think the smoke test should primarily be free from larger dependencies but IMO for the examples it should be alright :+1:

**Comment by Swat-SomeBug** [comment]
> If you still feel like adding a full-fledged hello triangle example, that would be great! I would leave it up to you if you still want to add a full-fledged example. As far as I can see, such an example could be tedious to setup without using GLFW.

This is what I meant when I wanted to link in `glfw`. The problem is, even to display some triangles, one needs to create a sort of graphics “context” + “viewport” which is platform dependent and even on Linux there is always X11 vs Wayland.
I just started handwriting a poor windowing implementation without `glfw` 😅 but if the smoke test is sufficient then I would really stop -> makes no sense to reinvent with all the bugs that come with it!

**Comment by Rookfighter** [comment]
Alright, sorry for the premature knowledge I pretended to have :smile: I guess the smoke test will then be enough.

**Comment by boris-kolpackov** [comment]
> No what I meant was to use the `*-Meta` packages. `glfw` depends on OpenGL and Vulkan, and current a big `if` block is used to set the necessary flags. Idea was to reuse these meta packages to avoid it.

Ah, got it, thanks for the clarification.

Regarding the "test via `glfw`" idea, I think I understand the issue now, which is that it will be really painful to write and maintain any kind of meaningful cross-platform test without using something higher-level like `glfw`. So in this light I think it may make sense to try and create a `glfw`-based test, if anyone is keen. I believe we shouldn't have the chicked-and-egg problem if we make such a test a separate package.

But I also think just a smoke test (which for now only works on GH CI) should be sufficient to publish to cppget.org.

**Comment by Rookfighter** [comment]
Published on cppget.org
